-- AlterTable
ALTER TABLE "Disponibilite" DROP COLUMN "dimanche",
DROP COLUMN "jeudi",
DROP COLUMN "lundi",
DROP COLUMN "mardi",
DROP COLUMN "mercredi",
DROP COLUMN "samedi",
DROP COLUMN "vendredi",
ADD COLUMN     "dimancheApresMidi" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "dimancheMatin" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "heureMidi" TEXT NOT NULL DEFAULT '13:00',
ADD COLUMN     "jeudiApresMidi" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "jeudiMatin" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "lundiApresMidi" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "lundiMatin" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "mardiApresMidi" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "mardiMatin" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "mercrediApresMidi" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "mercrediMatin" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "samediApresMidi" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "samediMatin" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "vendrediApresMidi" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "vendrediMatin" BOOLEAN NOT NULL DEFAULT true;
